[package]
name = "tinty"
description = "Change the theme of your terminal, text editor and anything else with one command!"
version = "0.24.0"
edition = "2021"
license = "MIT"
readme = "README.md"
authors = ["Jamy Golden <code@jamygolden.com>", "Tinted Theming <tintedtheming@proton.me>"]
homepage = "https://github.com/tinted-theming/tinty"
repository = "https://github.com/tinted-theming/tinty"
keywords = ["cli", "base16", "shell", "tinted-theming", "theme"]
categories = ["command-line-utilities"]

[dependencies]
anyhow = "1.0.89"
clap = { version = "4.5.23", features = ["derive"] }
clap_complete = { version = "4.5.40" }
hex_color = "3.0.0"
serde = { version = "1.0.216", features = ["derive"] }
serde_yaml = "0.9.33"
shell-words = "1.1.0"
strip-ansi-escapes = "0.2.0"
tinted-builder-rust = "0.12.1"
tinted-builder= "0.8.0"
tinted-scheme-extractor = "0.6.0"
toml = "0.8.19"
url = "2.5.4"
xdg = "2.5.2"
home = "0.5.11"
