[package]
name = "tinty"
description = "Change the theme of your terminal, text editor and anything else with one command!"
version = "0.8.1"
edition = "2021"
license = "MIT"
readme = "README.md"
authors = ["Jamy Golden <code@jamygolden.com>", "Tinted Theming <tintedtheming@proton.me>"]
homepage = "https://github.com/tinted-theming/tinty"
repository = "https://github.com/tinted-theming/tinty"
keywords = ["cli", "base16", "shell", "tinted-theming", "theme"]
categories = ["command-line-utilities"]

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.8", features = ["derive"] }
dirs = "5.0.1"
hex_color = "3.0.0"
serde = { version = "1.0.196", features = ["derive"] }
serde_yaml = "0.9.31"
shell-words = "1.1.0"
strip-ansi-escapes = "0.2.0"
toml = "0.8.9"
url = "2.5.0"
